apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done']
      containers:
      - name: backend
        image: sudssy/blog-backend:v3
        volumeMounts:
        - name: db-secret
          mountPath: /app/secrets
      volumes:
      - name: db-secret
        secret:
          secretName: db-password
          items:
          - key: password
            path: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: blog
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
